### ISSUE TITLE
Opening up certain parts of the app to endpoints?

### ISSUE THREAD

**Issue by AkeemAllen** [wavebeem/pkmn.help#198]
Hey @wavebeem. I hope you're doing well. First off, I want to say you've been doing a good job on this project. It immensely helped me solve a problem I was having.

To the point, have you/would you consider opening up parts of the project to endpoints?

### History
I was searching for a way to get defensive-type matchups for a pokemon wiki generation project I'm working on ([blaze-black-wiki](https://github.com/AkeemAllen/blaze-black-wiki)). It's based on the platinum renegade wiki that [FredericDlugi](https://github.com/FredericDlugi) developed. I kept coming up short until I discovered this project. Using it, I built a small API to cover my use case ([pokemon-matchups](https://github.com/AkeemAllen/pokemon-matchups)), but I think it'd be really useful to a lot of other people if this was a bigger/richer/more robust feature.

Any thoughts?
I'd even consider helping out with it myself if you have no problem with it 😅 
But of course, let me know

**Comment by wavebeem** [comment]
hi akeem! thanks 😄 

the short answer is no, i'm not interested in opening up the app to endpoints, at least not like JSON or some such. however i love supporting URL parameters, and i intentionally put as many parameters into the URL as i can so that folks can share links to the site. the site is entirely done thru static file hosting because it keeps things cheap, fast, and reliable. i don't want to get into the business of server side computation.

however, all of the code is [MIT licensed](https://github.com/wavebeem/pkmn.help/blob/master/LICENSE.md), and you're welcome to copy any parts you like, with attribution!

also, i've seen people fork my repository and change the types to better fit the custom pokemon game they're playing. that is explicitly allowed per the MIT license, and i think it's really cool! as a personal courtesy, my ask is that you at least change the title of the web page and the "More" screen so it doesn't look like i'm personally endorsing the forked version of the code.

if you're interested in contributing to this project, i would consider some kind of mode to allow alternate type matchups (https://github.com/wavebeem/pkmn.help/issues/159)

it's enough work that i haven't bothered doing it yet (i've never played a pokemon fan game before, so i haven't needed it), but i'm open to the possibility of custom types in the site... my main concern being that i don't want to get into the business of being pressured into adding countless fan game support into my site. but i'm happy to discuss this in more detail over in the other issue if that interests you.

i am interested in what you're working on though, so please feel free to continue discussing with me what your plans are and maybe there's some way i can help.

**Comment by AkeemAllen** [comment]
Hey @wavebeem 
Ok understood. Yeah, managing servers can be pretty cumbersome (Been through it). If you ever change your mind let me know, but of course, I will respect your wishes here. 🙏🏿 

🤔 That alternate-type matchup feature does sound interesting though. The project I'm working on would mostly target fan games and I was considering how I'd add more custom stuff down the line (pokemon, moves, etc). Therefore, this is definitely something I could get behind.

I can't say when though since I'm still elbow deep in this generator...and life in general lol. But if I ever come to tackle it you'll know of course!

**Comment by AkeemAllen** [comment]
## My project (Pokemon Rom hack wiki generator)
As for the project I'm working on, it's supposed to be a way for hack creators (or potentially anyone really) to generate documentation for their rom hacks. [Rough Idea in excalidraw](https://excalidraw.com/#json=sqyaZe1Bk86RJLflsu3up,D1R5EBgwqd87PC1vOX6v0g)

I was playing pokemon blaze black but found that the documentation only amounted to some rich text files. They were better than nothing but I felt they could be better. Then I remembered how I loved the docs for [platinum renegade](https://fredericdlugi.github.io/platinum-renegade-wiki/) so I decided to see if I could do the same for blaze black. Hence where I am right now. 

There are still a lot of kinks I'm working out (only started this project a month ago or so) so it's not quite ready for other contributions yet. However, talking to you has made me realize I should probably have some documentation so that it's easier for people to contribute when it's ready. So I guess, you've already contributed 😅 

It's kinda ironic really, _builds a documentation generator...doesn't write documentation_.

But once I'm at a certain stage I'll be sure to let u know where u can contribute if you're up for it 🤝

**Comment by wavebeem** [comment]
I don't really have the time to help with other projects per se, but if you have a specific use case like "I want to link to pkmn.help in a certain way" I might be interested 😄 

Sounds like a cool project, and I wish you well on it!

I'm going to close this issue since I think we've resolved the question. Feel free to make a new issue if you have more thoughts/ideas related to our discussion!

**Comment by AkeemAllen** [comment]
No worries
Thanks and the same to you!
