### ISSUE TITLE
Pokédex oddity for Meowstic

### ISSUE THREAD

**Issue by Madmadness65** [wavebeem/pkmn.help#222]
Meowstic in the Pokédex section is listed as the male variant, and the normal sprite reflects this. However, the Shiny sprite is that of the female Meowstic, and a somewhat low quality one at that.
![image](https://github.com/wavebeem/pkmn.help/assets/59298170/bb57bba5-f96a-4a2c-8bb5-ee78911fb504)

**Comment by wavebeem** [comment]
There's probably a few Pokémon like this, if I'm being honest. the current icons are sourced from a combination of PokéAPI and PokémonDB. I'll take a look and see if the PokéAPI folks have bundled any better icons.

I typically don't go manually sourcing the icons because it's a lot of work when there's >1000 Pokémon 😅

**Comment by wavebeem** [comment]
By the way, I'm looking into fixing this via #221 to switch to the Pokémon Home images.

I prefer the pixel art images mostly, but the Pokémon Home collection includes every monster in the same art style, and shiny versions! So it's likely I'll switch to that, but I'm still not 100% sure. I want to check what PokéAPI is doing these days.

I think they've actually had non-Nintendo artists contribute original pixel art in a matching style which is really cool imo.
