### ISSUE TITLE
Custom type changes

### ISSUE THREAD

**Issue by Clock-name** [wavebeem/pkmn.help#295]
This is probably the most robust checker for how much coverage offensive moves get down to the percent.

Makes me wonder, could you allow a mode for moving selected types around so you can say, drag and test if bug wasn't resisted by fighting?

Not like a big saved thing just temporary for the page/search, theory crafting is the heart of the site and i'd love to use it to cook up some theoretical balances future generations or if i play a romhack with an alternate type chart.

Edit: oops not to familiar with githubs layout and this is being worked on already, my bad, though i am asking for an on-the-fly instant mode rather then a longterm saved preset one.

**Comment by wavebeem** [comment]
This seems like a duplicate of #159.

If you look at that thread, you'll see lots of people have asked for this, and it's sat for quite a while.

This is simultaneously a tough change from a data side (types are hard coded to have specific interactions with skills, colors are hard coded based on the type, etc) AND a tough UI challenge (should I show a huge 12x12 grid to edit type matchups? should i show it as lists? should you be able to save this? what happens to the pokedex if you have custom types selected?)?

Add on that I don't actually play romhacks myself so I've never really needed anything like this, and you can see why I haven't made any big progress on this.

Thus far I've suggested to people to fork my site and add in their own custom type chart directly in the code, though I realize that's beyond most peoples skills and level of interest.

The answer is just a big "yeah, maybe", since I only work on this site in my free time and typically only as much as it is fun for me. Pokémon hasn't been in my game rotation for a while now, so I don't quite have the appetite for big changes like this lately...

If you're interested in contributing, I could probably give an overview of how to get it started, but I have to be honest that this is a big piece of work 😆

**Comment by Clock-name** [comment]
Wonder if it could be a final function ontop that just moves x things visually up or down one of the stages rather then cleanly added? Custom types themselves sure but maybe the lazy visual change way would work. But im just a dingus armchair guy, i can only code in doom lmao. Thanks for responding.

**Comment by wavebeem** [comment]
Yeahhh I'm not sure if I would want to implement "custom type matchups" rather than just full on "custom types" since I feel like many fan games end up adding a custom type or two anyway?

But I don't play fangames so I'm not really in touch with this.
