### ISSUE TITLE
Feature request: Streamline choosing best counter

### ISSUE THREAD

**Issue by IcedChill** [wavebeem/pkmn.help#70]
I am using your tool to pick a counter to Rocket leaders' Pokemon.  E.g. Salamence with Fire attack.

I first look at the bottom of the "Offense" tab for Fire.  This tells me that Rock/Fire/Water/Dragon would be a good type.

I then look at the top of the "Defense" tab which tells me that Ice would be the the best attack type to use.

So a really good candidate would be e.g. a Water Dragon with Ice Attack.

Seeing good defensive types next to good attack types would be very handy.

**Comment by wavebeem** [comment]
Hey, thanks for the feedback. If I'm understanding correctly, your suggestion is a page that lets you select defense types and offense types at the same time? And then shows you a curated "best" section?

**Comment by IcedChill** [comment]
Yes that’s correct.

**Comment by wavebeem** [comment]
I like the spirit of the idea, but I'm a little unsure what logic to use for a "best" section. I don't actually play Pokémon competitively or even all that much compared to a lot of the site's fans, so I typically stick to just presenting facts.

As it stands, this workflow is already supported fully. You can look at the _bottom_ of the offense tab and the top of the defense tab to get your ideal counter. Figuring out where to draw the line on "best" seems like something better left to the player, since they know more about the overall situation than this site ver would.

**Comment by IcedChill** [comment]
Yes that is pretty much how I am using your app currently.  On a PC I could run two instances side by side but on a phone I have to remember what is on each one and flip between the two.

Thank you for responding!

Robert

**Comment by wavebeem** [comment]
I don't have any plans to investigate a UI for this any time soon, so I'm going to close the issue. Thanks for your feedback!
